server:
    port: 8888
    
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Zell134/config.git
                    search-paths: config
                    username: Zell134
                    password: zellrus34
                    