server:
    port: 9090
    
spring:
    security:
        user:
            name: spring
            password: springPassword
    boot:
        admin:
            client:
                username: spring
                password: springPassword