spring:
    
    application:
        name: spring-in-action-service
        
    main:
        allow-bean-definition-overriding: true
        
    data:
        mongodb:
            host: 3.8.160.119
            port: 27017
            username: test
            password: test
            database: spring
            embedded:
                enabled: false
        rest:
            base-path: /api
            
    rabbitmq:
        host: 18.132.49.135
        port: 5672
        username: springUser
        password: CG56XNLI4PKxUBeIv611CEJC9GzXHSdHmFLP34kz
            
            
server:
    port: 0
    
eureka:
    client:
        service-url:
            defaultZone: http://3.10.154.98:8761/eureka
    instance:
        lease-renewal-interval-in-seconds: 20
        
management:
    endpoints:
        web:
            exposure:
                include: "*"
               
hystrix:
    dashboard:
        proxy-stream-allow-list: localhost
app:
    rabbit:
        topicExchangeName: topic-exchange
        queueName: queue
        routingKey: ingredients