spring:
    application:
        name: spring-in-action-service
    main:
        allow-bean-definition-overriding: true
    data:
        mongodb:
            host: 3.8.160.119
            port: 27017
            username: test
            password: test
            database: springDb
            embedded:
                enabled: false
        rest:
            base-path: /api
    rabbitmq:
        host: 18.132.49.135
        port: 5672
        username: springUser
        passwird: 12345678
            
server:
    port: 0
    
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/,
                         http://18.134.10.80:8761/eureka/,
                         http://18.134.10.80:8762/eureka
